/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frame.java
 *
 * Created on Aug 13, 2012, 4:19:40 PM
 */

package practica;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileFilter;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import sun.org.mozilla.javascript.ast.ForInLoop;

import org.jfree.chart.*;
import org.jfree.data.*;
import org.jfree.chart.plot.*;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;



/**
 *
 * @author andychaw
 */
public class Janela extends javax.swing.JFrame {

    /** Creates new form frame */
    public Janela() {
        initComponents();
        jTextArea1.setVisible(false);
        super.setSize(608, 390);
        super.setLocation(350, 100);

    }

  
   spe va= new spe();
  Tabla t = new Tabla();
   Yylex lexi;
   parser parsi;


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica1");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jTextPane1.setFont(new java.awt.Font("Candara", 0, 11)); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        jButton1.setText("↓");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        jButton2.setText("↑");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextPane2.setFont(new java.awt.Font("Candara", 0, 11)); // NOI18N
        jScrollPane4.setViewportView(jTextPane2);

        jButton5.setText("Grafica");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenuBar1.setFocusable(false);
        jMenuBar1.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem4.setText("Save As");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem5.setText("Close");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        Exit.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem7.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem7.setText("Compile");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem6.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem6.setText("Especifications");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem8.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem8.setText("Mistakes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem9.setText("Conteo");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenu3.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem10.setText("User Manual");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Candara", 0, 10)); // NOI18N
        jMenuItem11.setText("About");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, 206, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton5)
                        .addContainerGap(147, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String nombre="";
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 jTextPane1.setText("");
        jTextArea1.setText("");
        FileNameExtensionFilter f = new FileNameExtensionFilter("Type march", "march");
        JFileChooser jf = new JFileChooser();
        jf.setFileFilter(f);
        int files = jf.showSaveDialog(null);

        nombre = jf.getSelectedFile().getPath();
        String otro = jf.getSelectedFile().getName();

        if(new File(jf.getSelectedFile().getPath()).exists()) {
            if(JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(null,"The files named"+" "+"\""+otro+"\""+" "+"alredy exists."+"\n"+"Do you want to replace it?",null,JOptionPane.YES_NO_OPTION)) {
                
                BufferedWriter bw;
                try {
                    bw = new BufferedWriter(new FileWriter(nombre));
                    bw.write(jTextPane1.getText());
                    bw.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                
            } else {
                int fs = jf.showSaveDialog(null);
            }
            
        } else {
            BufferedWriter writes;
            try {
                writes= new BufferedWriter(new FileWriter(jf.getSelectedFile().getPath()+".march"));
                writes.write(jTextPane1.getText());
                writes.close();
                
            }catch(IOException ex){}
        }
        //------------------
            
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
int result = JOptionPane.showConfirmDialog(jTextPane1,"Guardar Trabajo, Antes de Salir");
if (result == JOptionPane.YES_OPTION) 
{
 SaveAs();

System.exit(0);
} else if (result == JOptionPane.NO_OPTION) {
System.exit(0); 
}
        
        
               // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed
String nombre2="";
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
  jTextPane1.setText("");
        jTextArea1.setText("");
        FileNameExtensionFilter f = new FileNameExtensionFilter("Type march", "march");
        JFileChooser jf = new JFileChooser();
        jf.setFileFilter(f);
        int files = jf.showOpenDialog(null);
        if (files == JFileChooser.APPROVE_OPTION) {
            nombre = jf.getSelectedFile().getPath();
            nombre2 = jf.getSelectedFile().getName();
            try{
                BufferedReader br = new BufferedReader(new FileReader(jf.getSelectedFile().getPath()));
                String line= br.readLine();
                while (line!= null) {
                    
                    StyledDocument doc = (StyledDocument)jTextPane1.getDocument();
                    Style style = doc.addStyle("StyleName", null);
                    StyleConstants.setBold(style, true);
                    StyleConstants.setForeground(style, Color.BLACK);
                    doc.insertString(doc.getLength(),line+"\n", style);
                    line = br.readLine();
                }
            } catch (Exception ex) {
                
            }
        }
  
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
System.out.print(nombre);
            BufferedWriter writes;
            try {
                writes= new BufferedWriter(new FileWriter(nombre));
                writes.write(jTextPane1.getText());
                writes.close();

            }catch(IOException ex){}
               
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        SaveAs();
        jTextPane1.setText("");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
      
    }//GEN-LAST:event_formComponentHidden

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jTextArea1.setVisible(true);
 super.setSize(608, 470);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextArea1.setVisible(false);
       super.setSize(608, 390);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

//System.out.println(nombre);
int result = JOptionPane.showConfirmDialog(jTextPane1,"Guardar Trabajo, Antes de Salir");
if (result == JOptionPane.YES_OPTION) {
 SaveAs();
 jTextPane1.setText("");
} else if (result == JOptionPane.NO_OPTION) {
nombre="";
jTextPane1.setText("");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
      File path = new File ("Manual.pdf");
        try {
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        va.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jTextPane2.setText("");
       
      practica.CUP$parser$actions.dto.clear();
      practica.CUP$parser$actions.vari.clear();
      practica.CUP$parser$actions.graphs.clear();
      jComboBox1.removeAllItems();
      
        try{
        lexi = new Yylex(new StringReader(jTextPane1.getText()));
        lexi.pane1= jTextPane2;
        lexi.nome = nombre2;
        parsi = new parser(lexi);
        parsi.parse();
        
        jTextArea1.setText("");
       }catch(Exception ex){ex.printStackTrace();}
 // *************************PRINT***********************      
      for (int g=0; g<practica.CUP$parser$actions.prnts.size();g++ )
            {
                
                String valu = practica.CUP$parser$actions.prnts.get(g).toString();
                //String p = valu.substring(1, valu.length()-2);
                //System.out.println(valu);
                jTextArea1.setVisible(true);
                super.setSize(608, 470);
                jTextArea1.append(valu +"\n");
            }  
      practica.CUP$parser$actions.prnts.clear();
  
//*****************************GRAFICAR******************   
      
      
        for (int i = 0; i < practica.CUP$parser$actions.graphs.size(); i++) 
        {
             jComboBox1.addItem(practica.CUP$parser$actions.graphs.get(i));
            
        }

    }//GEN-LAST:event_jMenuItem7ActionPerformed
   
   
    
    
    
    
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
       try{
     File path = new File("Errores_Archivo.html");
     Desktop.getDesktop().open(path);
     lexi.list1.clear();
     lexi.list2.clear();
     lexi.list3.clear();
     
     
        }
catch (IOException ex) {
}
                
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
    t.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
    About_Me am = new About_Me();
    am.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed
Tabla1 tab = new Tabla1();
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
      String selec = jComboBox1.getSelectedItem().toString();  
      int p = selec.indexOf("(");
      String ss = selec.substring(p+1,selec.length()-2);
      
        
           String ec[],eq[];
           String grado = "", pts="",ecua="";   
           ec= ss.split(",");
           grado = ec[0];
           pts = ec[1];
           ecua = ec[2];
         
          graph(grado, pts, ecua);

    
    }//GEN-LAST:event_jButton5ActionPerformed

     public void graph(String grado , String ptos, String ecua)
    {
    String eq[];
    int xs=0;
    Double ds ;
    eq= ecua.split(":");
    
    float g=Float.parseFloat(grado);
    int g1 = (int) g;
    float p = Float.parseFloat(ptos);
    int p1= (int) p;
    BufferedImage image;
    int contador = 0;
    
    contador = eq.length;
    System.out.println(contador);
        
    
    
    
    if(g1 == 1)
    {
         XYSeries series = new XYSeries("Grafico");
         while(xs<p1)
         {
             
             double ec = (Double.parseDouble(eq[0])* xs)+(Double.parseDouble(eq[1]));
             double ps = (double)xs; 
             series.add(ec, ps);
             xs++;
             System.out.println(ec);
          }
         XYDataset juegoDatos= new XYSeriesCollection(series);
         JFreeChart chart = ChartFactory.createXYLineChart("Grafico", "Y", "X", juegoDatos, PlotOrientation.HORIZONTAL, true, false, false);
            image= chart.createBufferedImage(600,600);
          ChartFrame frame = new ChartFrame("Grafico!", chart);
          frame.setSize(500, 500);
          frame.setVisible(true);
         
         
    } else if(g1 == 2)
    {
         XYSeries series = new XYSeries("Grafico");
         while(xs<p1)
         {
             if (contador==2)
             {
             double ec = (Double.parseDouble(eq[0])* Math.pow(xs, 2))+(Double.parseDouble(eq[1])*xs);
             double ps = (double)xs; 
             series.add(ec,ps);
             
             }else if (contador ==3)
             {
             double ec = (Double.parseDouble(eq[0])* Math.pow(xs, 2))+(Double.parseDouble(eq[1])*xs)+(Double.parseDouble(eq[2]));
             double ps = (double)xs; 
             series.add(ec,ps);
           
            
             }
            xs++;
         }
         XYDataset juegoDatos= new XYSeriesCollection(series);
         JFreeChart chart = ChartFactory.createXYLineChart("Grafico", "Y", "X", juegoDatos, PlotOrientation.HORIZONTAL, true, false, false);
            image= chart.createBufferedImage(600,600);
          ChartFrame frame = new ChartFrame("Grafico!", chart);
          frame.setSize(500, 500);
          frame.setVisible(true);   
    }else if(g1 == 3)
    {
         XYSeries series = new XYSeries("Grafico");
         while(xs<p1)
         {
             if (contador==4)
             {
             double ec = (Double.parseDouble(eq[0])* Math.pow(xs, 3))+(Double.parseDouble(eq[1])* Math.pow(xs, 2))+(Double.parseDouble(eq[2])*xs)+(Double.parseDouble(eq[3]));
             double ps = (double)xs; 
             series.add(ec,ps);
             
             }else if (contador ==3)
             {
              double ec = (Double.parseDouble(eq[0])* Math.pow(xs, 3))+(Double.parseDouble(eq[1])* Math.pow(xs, 2))+(Double.parseDouble(eq[2])*xs);
             double ps = (double)xs; 
             series.add(ec,ps);
           
            
             }else if (contador ==2)
             {
              double ec = (Double.parseDouble(eq[0])* Math.pow(xs, 3))+(Double.parseDouble(eq[1])* Math.pow(xs, 2));
             double ps = (double)xs; 
             series.add(ec,ps);
           
            
             }
             
             
             
             
             
             
            
             xs++;
             
          }
         XYDataset juegoDatos= new XYSeriesCollection(series);
         JFreeChart chart = ChartFactory.createXYLineChart("Grafico", "Y", "X", juegoDatos, PlotOrientation.HORIZONTAL, true, false, false);
            image= chart.createBufferedImage(600,600);
          ChartFrame frame = new ChartFrame("Grafico!", chart);
          frame.setSize(500, 500);
          frame.setVisible(true);
         
         
    }
    
    
    
    
//    if( g1 == 1)
//     {
//        
//         while(xs< p1)
//         {
//         Double a = Double.parseDouble(eq[0].toString())* xs + Double.parseDouble(eq[1].toString());
//         ds = (double)xs;
//         series.add(a,ds);
//         System.out.println(a +"--"+ds);
//         xs++;
//         }
//         
//     }
//   else 

        
    
    
        
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    void SaveAs()
    {
    FileNameExtensionFilter f = new FileNameExtensionFilter("Type march", "march");
        JFileChooser jf = new JFileChooser();
        jf.setFileFilter(f);
        int files = jf.showSaveDialog(null);
        nombre = jf.getSelectedFile().getPath();
        String otro = jf.getSelectedFile().getName();
        if(new File(jf.getSelectedFile().getPath()).exists()) {
            if(JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(null,"The files named"+" "+"\""+otro+"\""+" "+"alredy exists."+"\n"+"Do you want to replace it?",null,JOptionPane.YES_NO_OPTION)) {
                System.out.println(nombre);
                BufferedWriter bw = null;
                try {
                    File archivo = new File(nombre);
                    bw = new BufferedWriter(new FileWriter(archivo.getAbsolutePath()));
                    
                    bw.write(jTextPane1.getText());
                    bw.close();
                    
                } catch (Exception ex) {
                }
            } else  {
               
                int fs = jf.showSaveDialog(null);
               
               BufferedWriter writes;
            try {
                writes= new BufferedWriter(new FileWriter(jf.getSelectedFile().getPath()+".march"));
                writes.write(jTextPane1.getText());
                writes.close();
                
            }catch(IOException ex){}
                
            }
            
        } else {
            BufferedWriter writes;
            try {
                writes= new BufferedWriter(new FileWriter(jf.getSelectedFile().getPath()+".march"));
                writes.write(jTextPane1.getText());
                writes.close();
                
            }catch(IOException ex){}
        }
    }
    
    
    

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }
public static JTextPane getTextpane()
{
return jTextPane1;
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextPane jTextPane1;
    public static javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables

}
