package practik1_c1;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Aug 16 23:31:48 CST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int elc = 9;
  public static final int Fals = 6;
  public static final int comentario2 = 38;
  public static final int comentario1 = 37;
  public static final int ABI = 21;
  public static final int igual = 36;
  public static final int letra = 12;
  public static final int bol = 39;
  public static final int ys = 28;
  public static final int ints = 3;
  public static final int real = 20;
  public static final int ifs = 7;
  public static final int end = 19;
  public static final int chr = 30;
  public static final int whil = 14;
  public static final int numero = 17;
  public static final int then = 8;
  public static final int menos = 31;
  public static final int var = 2;
  public static final int EOF = 0;
  public static final int mas = 23;
  public static final int osi = 27;
  public static final int error = 1;
  public static final int cads = 40;
  public static final int fors = 11;
  public static final int por = 32;
  public static final int Enwhile = 16;
  public static final int str = 4;
  public static final int prnt = 25;
  public static final int paC = 35;
  public static final int id = 24;
  public static final int ndIf = 10;
  public static final int paA = 34;
  public static final int flt = 29;
  public static final int CER = 22;
  public static final int bgn = 18;
  public static final int Ver = 5;
  public static final int nxt = 13;
  public static final int div = 33;
  public static final int eif = 15;
  public static final int to = 26;
}

