package proy2;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 14 12:35:24 CST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int celeste = 40;
  public static final int nero = 38;
  public static final int textti = 27;
  public static final int image = 20;
  public static final int colbord = 19;
  public static final int comi = 49;
  public static final int fondo = 15;
  public static final int bord = 18;
  public static final int verdana = 44;
  public static final int numerito = 48;
  public static final int tamtit = 26;
  public static final int com = 64;
  public static final int geor = 43;
  public static final int s11 = 63;
  public static final int s10 = 62;
  public static final int rojo = 31;
  public static final int igual = 46;
  public static final int verde = 33;
  public static final int arial = 42;
  public static final int tre = 41;
  public static final int redo = 21;
  public static final int let = 50;
  public static final int vine = 14;
  public static final int typered = 22;
  public static final int vinc = 13;
  public static final int bic = 9;
  public static final int xmlc = 3;
  public static final int bia = 8;
  public static final int vina = 12;
  public static final int xmla = 2;
  public static final int azul = 32;
  public static final int rosa = 35;
  public static final int fuente = 17;
  public static final int typefont = 28;
  public static final int colf = 23;
  public static final int dosp = 47;
  public static final int EOF = 0;
  public static final int parc = 11;
  public static final int para = 10;
  public static final int error = 1;
  public static final int laranja = 39;
  public static final int gris = 36;
  public static final int morado = 34;
  public static final int typetxt = 30;
  public static final int tamf = 16;
  public static final int path = 25;
  public static final int logc = 7;
  public static final int semi = 51;
  public static final int loga = 6;
  public static final int s9 = 61;
  public static final int s8 = 60;
  public static final int s7 = 59;
  public static final int s6 = 58;
  public static final int inc = 5;
  public static final int s5 = 57;
  public static final int s4 = 56;
  public static final int typef = 29;
  public static final int ina = 4;
  public static final int s3 = 55;
  public static final int s2 = 54;
  public static final int s1 = 53;
  public static final int typeb = 24;
  public static final int dot = 52;
  public static final int branco = 37;
  public static final int courier = 45;
}

