package proy1_compi.Colores;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 13 20:00:11 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int colores = 2;
  public static final int coma = 13;
  public static final int hex = 8;
  public static final int red = 4;
  public static final int green = 6;
  public static final int color = 3;
  public static final int cer = 11;
  public static final int abi = 10;
  public static final int EOF = 0;
  public static final int numero = 14;
  public static final int error = 1;
  public static final int dponto = 12;
  public static final int hexc = 9;
  public static final int esce = 7;
  public static final int blue = 5;
}

